Add Google Auth .env filling for CD
aggie-coding-club/Rev-Registration pull request #342
Opened 2020-09-09 17:58 UTC by gannonprudhomme

## Description

Pretty straightforward - this adds the filling of the `.env` file for Google Auth.

## How to test

Per 6c7d749, I added a temp commit that makes the deployment run on PR so we can double check that this is actually working.

Note that frankly this is a terrible way of testing this (cause I could break the deployment), but lol yolo

## Related tasks

Closes #314

2020-09-09 19:15 UTC, gannonprudhomme commented
@ThatJuanGuy Google OAuth is currently giving a 500 Server Error when trying to log in, any idea why?

2020-09-09 19:31 UTC, gannonprudhomme commented
Oh just kidding I got it - we haven't applied the migrations on the server yet, so it doesn't know to create all the tables need for OAuth and such. Fixing it now by connecting to it through cloud_sql_proxy and running `python manage.py migrate`.

2020-09-14 17:35 UTC, gannonprudhomme commented
I force pushed so you can check this on GCP right now

2020-09-14 18:02 UTC, ryan-conn requested changes
Looks good, I think at some point in the future we'll want a `deployment` folder or something along those lines for docker files, shell scripts, etc. but that can be in a different PR after the coding club meeting so we can make sure nothing breaks

2020-09-14 18:02 UTC, ryan-conn commented on .github/workflows/deploy-workflow.yml
> +  pull_request:
Make sure to remove this

2020-09-14 18:10 UTC, ryan-conn approved these changes

2020-09-14 18:12 UTC, merged