Section select overrides include full sections
aggie-coding-club/Rev-Registration pull request #421
Opened 2020-10-25 05:34 UTC by ThatJuanGuy

## Description

Previously, when selecting a full section in section select and generating a schedule when "include full sections" was not selected, the section manually selected in section select would not be included. This PR makes it so that all sections manually selected in section select can be included in schedules regardless of whether include full sections is selected or not

## How to test

Select some courses and go to section select. Select full sections for that course. After you have selected the sections and courses, make sure "include full sections" is not selected on the configure card. Generate schedules. If the schedule generated includes the full sections you manually selected, it should be working. I also added one backend test.

## Related tasks

Doesn't close anything but a temp quality of life improvement meanwhile the "include full sections" checkbox is moved into the basic select of course cards and the configure card is removed.

2020-10-30 17:47 UTC, ryan-conn submitted a review, later dismissed
Small optimization and this looks good

2020-10-30 23:59 UTC, gannonprudhomme requested changes

2020-10-30 23:59 UTC, gannonprudhomme commented on autoscheduler/scheduler/create_schedules.py
> +    #if manually selected don't check if section is full before adding
god this is such a small nit pick (and really should be a linter rule) 
```suggestion
    # if manually selected don't check if section is full before adding
```

2020-10-31 20:37 UTC, gannonprudhomme approved these changes

2020-11-04 19:02 UTC, merged