Backend/400error
aggie-coding-club/Rev-Registration pull request #439
Opened 2020-10-28 04:12 UTC by ajayramsunder

## Description

Changes the 400 to a 200 

## Rationale

This makes it since the default is not logged in it returns a 200 

## How to test

Check the console when the website is rendered and see there is no 400 error 

## Screenshots

Before 
![image](https://user-images.githubusercontent.com/60300948/97390018-d65eaa80-18a9-11eb-9dce-2aedfd9f40f9.png)

After
![image](https://user-images.githubusercontent.com/60300948/97389997-cba41580-18a9-11eb-8940-35f9b9191f0e.png)

## Related tasks

Closes #358

2020-10-28 04:21 UTC, firejake308 commented
Don't we also need to update the frontend error handling?

2020-11-01 21:39 UTC, ryan-conn requested changes
Can you revert `timeUtil.ts` since it has nothing to do with this PR

2020-12-20 18:46 UTC, gannonprudhomme commented
Taking over this PR cause it is literally a 2 line change

2020-12-28 02:33 UTC, firejake308 approved these changes

2020-12-29 22:19 UTC, merged