Reverse schedule preview course direction
aggie-coding-club/Rev-Registration pull request #508
Opened 2021-02-14 18:58 UTC by gannonprudhomme

## Description

Reverses the schedule preview course direction to map the reversed CourseSelectColumn order. I _could_ probably add tests to this, but it's so dang simple that I really didn't think it was necessary.

## How to test

Add two courses, generate a schedule, and ensure they match up with the CourseSelectColumn direction

## Screenshots

|Before|After|
|--|--|
|![chrome_vL6NRpSMSS](https://user-images.githubusercontent.com/7295783/107886219-5c334f80-6eb3-11eb-8678-7b30c04515d5.png)|![chrome_bQYmDWQs7E](https://user-images.githubusercontent.com/7295783/107886225-5fc6d680-6eb3-11eb-9464-205276a24994.png)|

## Related tasks

Closes #499

2021-02-19 20:28 UTC, ryan-conn requested changes
Not much to comment on except a typo I noticed, works fine

Also probably worth pointing out that I should make the same change to the schedule details PR since it has the same reversed order as this

2021-02-19 20:28 UTC, ryan-conn commented on autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/ScheduleListItem/ScheduleListItem.tsx
> +          // Reverse the direction that the sections are displayed in to match to the CourseCards
```suggestion
          // Reverse the direction that the sections are displayed in to match the CourseCards
```

2021-03-08 00:52 UTC, ryan-conn commented
I just noticed we don't actually need this PR since I abstracted the logic mapping schedules to sections into its own function (so that I could reuse it for schedule details). Now that I added the reverse in the schedule details PR it also applies to the schedule list items

2021-03-08 00:53 UTC, gannonprudhomme commented
oh neato

2021-03-08 00:53 UTC, closed without merging