Set term to null on landing page
aggie-coding-club/Rev-Registration pull request #539
Opened 2021-04-18 22:07 UTC by gannonprudhomme

## Description

Re-adds the setting of null on the landing page that was accidentally removed in #515 so that the term in the navbar is reset to `Select Term`.

Also adds tests for it

## How to test

Do the action I did in my gif

## Screenshots

![set-term-null](https://user-images.githubusercontent.com/7295783/115162329-be493600-a057-11eb-9c93-68bfd3512708.gif)

## Related tasks

Closes #537

2021-04-18 22:08 UTC, gannonprudhomme commented
oh wtf I based this off of the wrong branch somehow

2021-04-25 17:32 UTC, ryan-conn requested changes
Other than a duplicated commit, this is fine

2021-04-25 17:32 UTC, ryan-conn commented on autoscheduler/frontend/src/components/SchedulingPage/CourseSelectColumn/CourseSelectCard/ExpandedCourseCard/SectionSelect/SectionSelect.tsx
> +        }}
It seems like you accidentally duplicated this change between this PR and #536 so remove the commit

2021-04-25 18:26 UTC, ryan-conn approved these changes

2021-04-25 18:28 UTC, merged