Fixed bug with infinitely growing cards
aggie-coding-club/Rev-Registration pull request #590
Opened 2021-05-31 01:30 UTC by firejake308

## Description

This bug was originally discovered in #580, read the comments there for more context.

## Rationale

I elected to address both of the issues by adding 2px of padding-bottom to `.section-rows`, since we were going to do it anway in #523 

## How to test

Bug 1 - Disable, then enable a course card repeatedly. The card should not grow. There is also a Jest test to ensure that this bug does not relapse.

Bug 2 - Open SPAN 301 in Chrome (not Firefox), and make sure your window is big enough to accommodate all sections without scrolling. If not, zoom out, then close and open the course card. There should be no scroll bar in the list of sections.

## Screenshots

|Before|After|
|--|--|
|![image](https://user-images.githubusercontent.com/10082177/120127690-a6e88700-c185-11eb-8d88-7ed946c7ba90.png)|![image](https://user-images.githubusercontent.com/10082177/120127468-114cf780-c185-11eb-9250-e880af09d932.png)|

2021-06-06 17:59 UTC, gannonprudhomme commented
You have my commits from #580 in here - you'll need to hard reset and cherry-pick these commits

2021-06-06 18:03 UTC, gannonprudhomme requested changes
![shift-bug](https://user-images.githubusercontent.com/7295783/120935244-a6d11580-c6b6-11eb-9926-3d17052731a4.gif)

this does still seem to be occurring in Chrome unfortunately :( Also occurs in Firefox for me, but it doesn't do it on the initial render like Chrome does

2021-06-06 21:46 UTC, firejake308 commented
![image](https://user-images.githubusercontent.com/10082177/120939069-a4cd7d80-c6db-11eb-9f84-09a624f648d6.png)

Now that you mention it, I am also seeing the bug as well. Time to debug, I guess

2021-06-06 21:59 UTC, firejake308 commented
Okay, looks like the problem was that on each render, I was setting the element `height` to be equal to the current `scrollHeight`, which actually included the element height + padding. By changing the padding to margin, it seems to resolve both bugs on my computer.

2021-06-28 19:57 UTC, gannonprudhomme commented
Note that you still have my commits from #580 in here - otherwise I believe this is good to go

2021-06-29 00:01 UTC, firejake308 commented
Rebased with master

2021-07-06 20:33 UTC, gannonprudhomme approved these changes

2021-07-06 20:39 UTC, merged