Show schedule hours
aggie-coding-club/Rev-Registration pull request #595
Opened 2021-06-21 21:32 UTC by ryan-conn

## Description
Shows hours for schedules both below the schedule and in schedule details

## Screenshots
|Before (below schedule) | After |
|--|--|
| ![image](https://user-images.githubusercontent.com/28655462/122830065-6e802880-d2ad-11eb-81b2-6df676efdef2.png) | ![image](https://user-images.githubusercontent.com/28655462/122829912-37aa1280-d2ad-11eb-95ef-83e7f7201100.png) |

| Before (details) | After |
|-|-|
| ![image](https://user-images.githubusercontent.com/28655462/122830509-0b42c600-d2ae-11eb-9c37-e0a156b9d78c.png) | ![image](https://user-images.githubusercontent.com/28655462/122830536-14cc2e00-d2ae-11eb-8204-9222e01f82be.png) |

## Related tasks
Closes #557.

2021-07-20 22:32 UTC, gannonprudhomme requested changes
A few unused css classes but code wise this looks good.

Some visual comments that we can discuss in the meeting:
- Instructor text wrapping looks sort of funny
- Not sure if I want meeting days to be centered or not

2021-07-20 22:32 UTC, gannonprudhomme commented on autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/ScheduleDetails/ScheduleDetails.css
> +
Pretty sure these are unused?

2021-07-20 22:32 UTC, gannonprudhomme commented on autoscheduler/frontend/src/components/SchedulingPage/SchedulePreview/ScheduleDetails/ScheduleDetails.css
> +}
Seems unused

2021-07-24 17:15 UTC, ryan-conn commented
The most recent set of commits fixes the unused CSS classes and improves the grid layout of schedule details in a couple ways:
- Instructional method icons are now included in the grid to make spacing more consistent and make it possible to use a single unified grid instead of one per section
- Instructor names will overflow with ellipsis instead of wrapping and causing layout issues, see the following examples (screenshots are at 1024x768 which is lower than pretty much anyone will ever use to demonstrate how little wrapping is actually needed, ignore the scrollbar as it's a devtools rendering issue):
![image](https://user-images.githubusercontent.com/28655462/126876121-0a42b565-c0be-4109-9106-41620bc49dd3.png)
![image](https://user-images.githubusercontent.com/28655462/126876131-313c5644-df71-4937-9f33-f174260f736b.png)

2021-07-26 22:54 UTC, gannonprudhomme approved these changes
Great solution to the wrapping problem! Works much better than allowing two lines

2021-07-30 14:42 UTC, merged